services:
  agendamentoconsulta_db:
    image: postgres:18.0-alpine
    container_name: agendamento_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db_agendamento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0301

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s       # Tenta a cada 10 segundos
      timeout: 5s
      retries: 10         # Aumentamos as tentativas para 10
      start_period: 90s   # <-- A GRANDE MUDANÃ‡A