services:
  agendamentoconsulta_db:
    image: postgres:18.0-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=db_agendamento
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0301