version: '3.8'

services:
  agendamentoconsulta_db:
    image: postgres:18.0-alpine
    container_name: agendamento_db
    environment:
      POSTGRES_DB: db_agendamento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0301
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-spring:
    image: apiconsulta-api-spring
    container_name: api-consulta
    depends_on:
      agendamentoconsulta_db:
        condition: service_healthy
    ports:
      - "8080:8080"
