services:
  agendamentoconsulta_db:
    container_name: meu-postgres-local
    image: postgres:18.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_agendamento
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0301